FROM debian:buster

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y nginx \
	openssl \
	vim

# Pour créer une connexion securisée, je génère un
# un certificat et une clé avec open SSL.

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/bgales.crt\
	-keyout /etc/nginx/ssl/bgales.key\
	-subj "/C=FR/ST=PACA/L=Nice/O=42/OU=Atreides/CN=bgales/EA=secret"

# La commande -nodes créé une clé
# sans mdp pour qu'openssl ne query pas.
# Pareil pour -subj, on prérempli un formulaire dans la commande
# pour ne pas interrompre le build.

RUN mkdir -p /var/run/nginx
COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html

EXPOSE 443
CMD [ "nginx", "-g", "daemon off;" ]
