FROM debian:buster

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y nginx \
	openssl \
	vim


RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/bgales.crt\
	-keyout /etc/nginx/ssl/bgales.key\
	-subj "/C=FR/ST=PACA/L=Nice/O=42/OU=Atreides/CN=bgales/EA=secret"

RUN mkdir -p /var/run/nginx
COPY conf/nginx.conf /etc/nginx/nginx.conf
RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html

EXPOSE 443
CMD [ "nginx", "-g", "daemon off;" ]
